### ISSUE TITLE
Patches change the Python ABI

### ISSUE THREAD

**Issue by haypo** [haypo/pytracemalloc#1]
Ionel Cristian Mărieș wrote me that the patched Python has a different binary ABI, see the compilation log:
https://launchpadlibrarian.net/168954360/buildlog_ubuntu-quantal-amd64.python2.7_2.7.3-5ubuntu4.4%2Btracemalloc1.0%2Bppa1_FAILEDTOBUILD.txt.gz

The following symbols are missing:

<pre>
(optional)init_hashlib
(optional)init_ssl
_PyMem_DebugFree
_PyMem_DebugMalloc
_PyMem_DebugRealloc
_PyObject_DebugCheckAddress
_PyObject_DebugCheckAddressApi
_PyObject_DebugDumpAddress
_PyObject_DebugFree
_PyObject_DebugFreeApi
_PyObject_DebugMalloc
_PyObject_DebugMallocApi
_PyObject_DebugRealloc
_PyObject_DebugReallocApi
</pre>

**Comment by gpshead** [comment]
should this issue still be open given the above commit?

**Comment by haypo** [comment]
It looks like Python 2.6 & Python 2.7 patches are ok, but not the Python 3.3 patch. Are you interested to update the patch?

**Comment by gpshead** [comment]
Nah i'm just interested in 2.7. I already use 3.4 when using 3 :)

**Comment by haypo** [comment]
> Nah i'm just interested in 2.7. I already use 3.4 when using 3 :)

Like me. No major OS use Python 3.3 anymore.
