### ISSUE TITLE
install pytracemalloc 1.2 failure 

### ISSUE THREAD

**Issue by zhizhongzhiwai** [haypo/pytracemalloc#4]
ubuntu12.04 32, python 2.7.6
pip install pytracemalloc==1.2, here is error message:

![image](https://cloud.githubusercontent.com/assets/6985180/5259240/4d42a96a-7a38-11e4-8ff9-a75ab4ec09cd.png)

**Comment by haypo** [comment]
No reply from the original poster, I close the bug.
