### ISSUE TITLE
Feature request: load() shouldn't require patched python

### ISSUE THREAD

**Issue by andresriancho** [haypo/pytracemalloc#5]
I'm running pytracemalloc to collect data in one server and then want to analyze the data in other workstations. It shouldn't be a requirement for me to install the patched python just for me to `load()` and analyze a cpickle file

**Comment by haypo** [comment]
I agree that it's not convinient. The tracemallocqt project embeds a light "tracemalloc" module which only provides functions to load a snapshot.
http://pytracemalloc.readthedocs.org/tracemallocqt.html

It's maybe possible to modify tracemalloc.py to support missing _tracemalloc: only raise an exception when tracing is used?

**Comment by haypo** [comment]
Are you interested to work on patch?

**Comment by andresriancho** [comment]
Not interested in working on the patch, sorry, no time at this moment :(

**Comment by haypo** [comment]
The _tracemalloc module is required to get the __version__ symbol :-/ Since this bug was only reported once, I'm closing it. You can use Python 3.4 which has a builtin tracemalloc module and so works nice for your use case.
